[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js SSR 라우팅 대응
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_router"
  status = 200
